package com.example.wax.data.local

import androidx.room.Database
import androidx.room.RoomDatabase

/**
 * Room database for the Wax app's album listening history.
 *
 * The [@Database] annotation tells Room to generate a concrete implementation of this
 * abstract class. The annotation parameters define the database schema:
 * - **[entities]:** The list of [@Entity]-annotated classes whose fields map to table
 *   columns. Adding or removing a class here triggers a schema change that requires a
 *   migration (or `fallbackToDestructiveMigration()` in debug builds).
 * - **[version]:** An integer that must be incremented whenever the schema changes
 *   (new table, new/removed column, changed type). Room compares this value at runtime
 *   against the version stored in the database file and runs registered migrations if
 *   they differ. Starting at `1` is the convention for a brand-new database.
 * - **[exportSchema]:** When `true`, Room writes a JSON snapshot of the schema to the
 *   `schemas/` directory at compile time. These snapshots are used by Room's migration
 *   tests to verify that migrations produce the expected schema. Always `true` in
 *   production to keep a full schema history.
 *
 * The single instance of this class is created by Hilt in
 * [com.example.wax.core.di.DatabaseModule] using [androidx.room.Room.databaseBuilder]
 * and is provided as a [@Singleton] for the lifetime of the process.
 */
@Database(entities = [AlbumHistoryEntity::class], version = 1, exportSchema = true)
abstract class AlbumHistoryDatabase : RoomDatabase() {

    /**
     * Returns the [AlbumHistoryDao] implementation generated by Room.
     *
     * Room generates a concrete class that implements this abstract function; callers
     * receive the DAO via Hilt injection (see [com.example.wax.core.di.DatabaseModule])
     * and never instantiate it directly.
     */
    abstract fun albumHistoryDao(): AlbumHistoryDao
}
