package com.example.wax.core.di

import android.content.Context
import androidx.room.Room
import com.example.wax.data.local.AlbumHistoryDao
import com.example.wax.data.local.AlbumHistoryDatabase
import dagger.Module
import dagger.Provides
import dagger.hilt.InstallIn
import dagger.hilt.android.qualifiers.ApplicationContext
import dagger.hilt.components.SingletonComponent
import javax.inject.Singleton

/**
 * Hilt module that provides the Room database and its DAO for the album listening history.
 *
 * [@Module] marks this object as a source of `@Provides`-annotated bindings for Hilt.
 * [@InstallIn(SingletonComponent::class)] scopes all bindings to the application lifetime,
 * meaning the database and DAO are created once and reused for the entire process.
 *
 * Room requires a single database instance per database file; using `@Singleton` here
 * prevents multiple instances from being created concurrently, which could corrupt the
 * WAL journal or cause "database is locked" errors under concurrent writes.
 */
@Module
@InstallIn(SingletonComponent::class)
object DatabaseModule {

    /**
     * Creates and provides the [AlbumHistoryDatabase] Room database instance.
     *
     * [Room.databaseBuilder] creates the SQLite database file `wax_album_history.db`
     * in the app's internal database directory (`/data/data/<package>/databases/`).
     * The file is private to the app — no `READ_EXTERNAL_STORAGE` permission is needed.
     *
     * `@Singleton` ensures Room builds the database only once per process, reusing the
     * same connection pool and WAL journal across all injection sites.
     *
     * @param context Application context used to resolve the database file path.
     * @return The application-scoped [AlbumHistoryDatabase] singleton.
     */
    @Provides
    @Singleton
    fun provideAlbumHistoryDatabase(@ApplicationContext context: Context): AlbumHistoryDatabase =
        Room.databaseBuilder(
            context,
            AlbumHistoryDatabase::class.java,
            "wax_album_history.db"
        ).build()

    /**
     * Provides the [AlbumHistoryDao] by calling [AlbumHistoryDatabase.albumHistoryDao].
     *
     * The DAO is not `@Singleton` because it is a thin proxy object generated by Room —
     * creating a new proxy instance each time it is requested is cheap, and scoping it
     * to `SingletonComponent` via the database is sufficient to ensure a single underlying
     * SQLite connection. Room's generated DAO implementation is thread-safe.
     *
     * @param db The [AlbumHistoryDatabase] instance provided by [provideAlbumHistoryDatabase].
     * @return The Room-generated [AlbumHistoryDao] implementation.
     */
    @Provides
    fun provideAlbumHistoryDao(db: AlbumHistoryDatabase): AlbumHistoryDao = db.albumHistoryDao()
}
